# Stage 1: Build
FROM node:20 AS build
WORKDIR /app

# Copia dependências
COPY package*.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Compila a aplicação
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
