server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para o backend se necessário (opcional, já que o frontend usa localhost:8080 no environment)
    # location /api/v1 {
    #     proxy_pass http://backend:8080;
    # }
}
