version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: sga-mysql
    restart: always
    environment:
      MYSQL_DATABASE: sga_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: sga_user
      MYSQL_PASSWORD: sga_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: sga-backend
    working_dir: /app
    command: mvn quarkus:dev -Dquarkus.http.host=0.0.0.0 -Ddebug=5006 -DdebugHost=0.0.0.0 -Dsuspend=false -Dquarkus.analytics.disabled=true
    environment:
      MYSQL_USER: sga_user
      MYSQL_PASSWORD: sga_password
      DEBUG_MODE: "true"
    ports:
      - "8080:8080"
      - "5006:5006"
    volumes:
      - ./backend:/app
      - maven_cache:/root/.m2
    depends_on:
      mysql-db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sga-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  maven_cache:
