# Configuração de Banco de Dados MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=sga_user
quarkus.datasource.password=sga_password
quarkus.datasource.jdbc.url=jdbc:mysql://sga-mysql:3306/sga_db

# Hibernate Dev Services - Disable to use our own MySQL container
quarkus.datasource.devservices=false

# Configuração JWT

mp.jwt.verify.issuer=https://sga-api.com
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

# Seguranca habilitada para validar JWT nas rotas protegidas
quarkus.security.enabled=true
#quarkus.http.auth.permission.permit1.paths=/*
#quarkus.http.auth.permission.permit1.policy=permit

# Se estiver usando OIDC
quarkus.oidc.enabled=false

# Variáveis de Ambiente do Sistema
sga.system.debugMode=${DEBUG_MODE:true}

# Allow cross-origin requests from Angular frontend
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.auth.permission.options.paths=/*
quarkus.http.auth.permission.options.methods=OPTIONS
quarkus.http.auth.permission.options.policy=permit

quarkus.http.auth.permission.public.paths=/api/v1/auth/login
quarkus.http.auth.permission.public.policy=permit

quarkus.http.auth.permission.authenticated.paths=/api/v1/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.log.level=INFO
quarkus.log.category."org.hibernate".level=DEBUG
quarkus.log.category."io.quarkus".level=TRACE
